services:
  new-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-website
    network_mode: host
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    restart: unless-stopped
